### ISSUE TITLE
unable to allocate file descriptor table - out of memoryAborted error while buildinf docker

### ISSUE THREAD

**Issue by muhammadabdullah007git** [BerryFarm/berrymuch#68]
=> ERROR [ 8/15] RUN Xvfb :1 & ./sdkinstall --install 10.3.1.995                                                                                                  4.2s
------                                                                                                                                                                  
 > [ 8/15] RUN Xvfb :1 & ./sdkinstall --install 10.3.1.995:
1.180 library initialization failed - unable to allocate file descriptor table - out of memoryAborted (core dumped)
------
Dockerfile:39
--------------------
  37 |     WORKDIR /root/bbndk
  38 |     ENV DISPLAY=:1
  39 | >>> RUN Xvfb :1 & ./sdkinstall --install 10.3.1.995  
  40 |     
  41 |     RUN echo "source /root/bbndk/bbndk-env_10_3_1_995.sh" >> /root/.bashrc
--------------------
ERROR: failed to solve: process "/bin/sh -c Xvfb :1 & ./sdkinstall --install 10.3.1.995" did not complete successfully: exit code: 134

while building docker this error occurring. not getting what to do. i am using manjaro linux. intel q8400 cpu and 4gb of ram.

**Comment by karawitan** [comment]
Please tell how to reproduce

**Comment by karawitan** [comment]
Ok did some progress on build docker-image 

The sdk cannot be download from Blackberry.com anymore:

http://downloads.blackberry.com/upr/developers/update/bbndk/install_descriptor.xml




```
karawitan@shinwey:~/berrymuch$ docker build -t test:0.1 -f Dockerfile .
[+] Building 481.4s (12/19)
 => [internal] load build definition from Dockerfile                                                                                                               0.0s
 => => transferring dockerfile: 1.19kB                                                                                                                             0.0s
 => [internal] load .dockerignore                                                                                                                                  0.0s
 => => transferring context: 98B                                                                                                                                   0.0s
 => [internal] load metadata for docker.io/i386/ubuntu:18.04                                                                                                       0.9s
 => [auth] i386/ubuntu:pull token for registry-1.docker.io                                                                                                         0.0s
 => [ 1/15] FROM docker.io/i386/ubuntu:18.04@sha256:fc896f56642f382e99601461c683dee1534f0d4cb7e17bcb3494d5ed0f3a8a06                                               0.0s
 => CACHED [ 2/15] RUN export DEBIAN_FRONTEND=noninteractive                                                                                                       0.0s
 => CACHED [ 3/15] RUN apt-get -q update                                                                                                                           0.0s
 => CACHED [ 4/15] RUN apt-get -yq install     subversion     curl     tar     gzip     bzip2     ruby     git     subversion     curl     texinfo     autopoint   0.0s
 => CACHED [ 5/15] WORKDIR /root                                                                                                                                   0.0s
 => [ 6/15] RUN wget https://archive.org/download/native-SDK-for-blackberry10/Momentics%20IDE/momentics-2.1.2-201503050937.linux.x86.run ;  chmod +x momentics-  473.9s
 => [ 7/15] WORKDIR /root/bbndk                                                                                                                                    0.0s
 => ERROR [ 8/15] RUN Xvfb :1 & ./sdkinstall --install 10.3.1.995                                                                                                  6.5s
------
 > [ 8/15] RUN Xvfb :1 & ./sdkinstall --install 10.3.1.995:
#0 5.679 com.qnx.tools.ide.sdk.manager.core.internal.installdescriptor.InstallDescriptor$InstallDescriptorLoadException: http://downloads.blackberry.com/upr/developers/update/bbndk/install_descriptor.xml
#0 5.679        at com.qnx.tools.ide.sdk.manager.core.internal.installdescriptor.InstallDescriptor.load(InstallDescriptor.java:125)
#0 5.679        at com.qnx.tools.ide.sdk.manager.core.internal.installdescriptor.InstallDescriptor.<init>(InstallDescriptor.java:42)
#0 5.679 	at com.qnx.tools.ide.sdk.manager.core.internal.SDKManager.doRefresh(SDKManager.java:530)
#0 5.679 	at com.qnx.tools.ide.sdk.manager.core.internal.SDKManager.refresh(SDKManager.java:510)
#0 5.679 	at com.qnx.tools.ide.sdk.installer.app.SDKInstallerApplication.start(SDKInstallerApplication.java:267)
#0 5.679 	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
#0 5.679 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
#0 5.679 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
#0 5.682 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:354)
#0 5.682 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:181)
#0 5.682 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
#0 5.682 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
#0 5.682 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
#0 5.682 	at java.lang.reflect.Method.invoke(Unknown Source)
#0 5.682 	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:636)
#0 5.682 	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591)
#0 5.682 	at org.eclipse.equinox.launcher.Main.run(Main.java:1450)
#0 5.682 Caused by: java.io.FileNotFoundException: http://downloads.blackberry.com/upr/developers/update/bbndk/install_descriptor.xml
#0 5.682 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
#0 5.682 	at java.net.URL.openStream(Unknown Source)
#0 5.682 	at com.qnx.tools.ide.sdk.manager.core.internal.installdescriptor.InstallDescriptor.load(InstallDescriptor.java:58)
#0 5.682 	... 16 more
------
Dockerfile:39
--------------------
  37 |     WORKDIR /root/bbndk
  38 |     ENV DISPLAY=:1
  39 | >>> RUN Xvfb :1 & ./sdkinstall --install 10.3.1.995
  40 |
  41 |     RUN echo "source /root/bbndk/bbndk-env_10_3_1_995.sh" >> /root/.bashrc
--------------------
ERROR: failed to solve: process "/bin/sh -c Xvfb :1 & ./sdkinstall --install 10.3.1.995" did not complete successfully: exit code: 1
```


```
karawitan@shinwey:~/berrymuch$ git diff Dockerfile
diff --git a/Dockerfile b/Dockerfile
index ea97dccbb..2231d863a 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -29,7 +29,7 @@ RUN apt-get -yq install \

 WORKDIR /root

-RUN wget https://archive.org/download/native-SDK-for-blackberry10/Momentics%20IDE/momentics-2.1.2-201503050937.linux.x86_64.run ; \
+RUN wget https://archive.org/download/native-SDK-for-blackberry10/Momentics%20IDE/momentics-2.1.2-201503050937.linux.x86.run ; \
        chmod +x momentics-2.1.2-201503050937.linux.x86.run ; \
        yes 'y' | LESS='+q' ./momentics-2.1.2-201503050937.linux.x86.run ; \
        rm momentics-2.1.2-201503050937.linux.x86.run
```

**Comment by karawitan** [comment]
This post might help us

https://sizeof.cat/post/blackberry-10-development-in-2022/

**Comment by muhammadabdullah007git** [comment]
@karawitan thanks. i also got that error. is there any solution ?
```
com.qnx.tools.ide.sdk.manager.core.internal.installdescriptor.InstallDescriptor$InstallDescriptorLoadException: http://downloads.blackberry.com/upr/developers/update/bbndk/install_descriptor.xml
	at com.qnx.tools.ide.sdk.manager.core.internal.installdescriptor.InstallDescriptor.load(InstallDescriptor.java:125)
	at com.qnx.tools.ide.sdk.manager.core.internal.installdescriptor.InstallDescriptor.<init>(InstallDescriptor.java:42)
	at com.qnx.tools.ide.sdk.manager.core.internal.SDKManager.doRefresh(SDKManager.java:530)
	at com.qnx.tools.ide.sdk.manager.core.internal.SDKManager.refresh(SDKManager.java:510)
	at com.qnx.tools.ide.sdk.installer.app.SDKInstallerApplication.start(SDKInstallerApplication.java:267)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:354)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:181)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:636)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1450)
Caused by: java.io.FileNotFoundException: http://downloads.blackberry.com/upr/developers/update/bbndk/install_descriptor.xml
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.URL.openStream(Unknown Source)
	at com.qnx.tools.ide.sdk.manager.core.internal.installdescriptor.InstallDescriptor.load(InstallDescriptor.java:58)
	... 16 more
```

**Comment by karawitan** [comment]
The solution is either:
  - find the original files .zip for linux, then simply unzip them.
  - get the files below /root/bbndk from an archive of this image:

yamsergey/bb10-ndk                                     0.6                      c31795440942   2 years ago     6.76GB

I think we will have to stick to the second solution ..

**Comment by muhammadabdullah007git** [comment]
@karawitan thanks. Let's see if works

**Comment by muhammadabdullah007git** [comment]
@karawitan thanks. Let's see if works. There is a target_10_3_1_995 folder on clitools. What is this for ?

**Comment by karawitan** [comment]
https://ipfs.io/ipfs/QmQ5eEFh1eUybwWmo8Qi3JMpzTnzRb4rsNW7Te4dKKPXiM/
Please be patient, it's more than 6Go

**Comment by muhammadabdullah007git** [comment]
@karawitan thanks. Now BB has stopped it's service. So what to do !

**Comment by karawitan** [comment]
Ok closing the issue, as the original error is solved. Issue appears with arch based distributions for docker host. Using debian based fixed the issue.
